stages:
  - test
  - lint

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

test:rust:
  stage: test
  image: rust:latest
  script:
    - cargo build --release
    - cargo test
  tags:
    - docker

lint:rust:
  stage: lint
  image: rust:latest
  script:
    - cargo clippy -- -D warnings
    - cargo fmt --check
  tags:
    - docker
